### ISSUE TITLE
docker-build extension files version mismatch

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/stack-eda-services#5]
if i try `docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-build/docker-compose-build-compute.yml build` like is suggested i should be able to do in the README i see an error `ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.5 but extension file ./docker-build/docker-compose-build-compute.yml uses version 1`

**Comment by ryanrdoherty** [comment]
Fixed.
